GRANT CREATE VIEW TO scott;


SHOW CON_NAME;
ALTER SESSION SET CONTAINER = XEPDB1;
SHOW CON_NAME;
GRANT CREATE VIEW TO SCOTT;

SELECT *
FROM DBA_SYS_PRIVS
WHERE GRANTEE = 'SCOTT'
  AND PRIVILEGE = 'CREATE VIEW';